---
# tasks file for conf_wp_base

  # MySQL WP config
    - name: Creates database for WordPress
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_unix_socket: "{{ mysql_socket }}"
      tags: [ wordpress ]

    - name: Create MySQL user for WordPress
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        host: "%"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_unix_socket: "{{ mysql_socket }}"
      tags: [ wordpress ]

#    - name: Copy config sql file for AuthLDAP Plugin
#      copy:
#        src: "files/authLdap_conf.sql"
#        dest: "/tmp"
#      tags: [ wp_config ]

#    - name: Register AuthLDAP Plugin in database
#      shell: mysql -u {{ mysql_user }} -p {{ mysql_password }} -h {{ mysql_host }} -P {{ mysql_port }} {{ mysql_db }} < /tmp/authLdap_conf.sql
#      ignore_errors: yes
#      tags: [ wp_config ]
