---
# tasks file for web

    - name: Install LAP Packages
      apt: name={{ item }} state=latest
      loop: [ 'apache2', 'php', 'php-mysql', 'libapache2-mod-fcgid', 'unzip' ]
      tags: [ web_install ]

    - name: Install PHP Extensions
      apt: name={{ item }} state=latest
      loop: "{{ php_modules }}"
      tags: [ web_install ]

    - name: Increase PHP memory and file limits
      lineinfile:
        path: "/etc/php/{{ php_ver }}/apache2/php.ini"
        state: present
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^memory_limit', line: 'memory_limit = 256M' }
        - { regexp: '^upload_max_filesize', line: 'upload_max_filesize = 32M' }
        - { regexp: '^post_max_size', line: 'post_max_size = 32M' }

  # Apache Configuration
    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ http_owner }}"
        group: "{{ http_group }}"
        mode: '0755'
      tags: [ apache_conf ]

    - name: Set up Apache VirtualHost
      template:
        src: "templates/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache
      tags: [ apache_conf ]

    - name: Enable rewrite module
      shell: /usr/sbin/a2enmod rewrite
      notify: Restart Apache
      tags: [ apache_conf ]

    - name: Disable default php module and pre-fork mpm module
      shell: /usr/sbin/a2dismod php{{ php_ver }} mpm_prefork
      notify: Restart Apache
      tags: [ apache_conf ]

    - name: Enable event mpm module
      shell: /usr/sbin/a2enmod mpm_event
      notify: Restart Apache
      tags: [ apache_conf ]

    - name: Enable php-fpm module
      shell: /usr/sbin/a2enconf php{{ php_ver }}-fpm
      notify: Reload Apache
      tags: [ apache_conf ]

    - name: Enable proxy and proxy_fcgi modules
      shell: /usr/sbin/a2enmod proxy_fcgi
      notify: Restart Apache
      tags: [ apache_conf ]

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache
      tags: [ apache_conf ]

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      notify: Restart Apache
      tags: [ apache_conf ]

  # UFW Configuration for http
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp
      tags: [ system ]
