all:
 vars:
  ansible_user: vagrant
  ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
 children:
  db:
   hosts:
    mysql:
     ansible_host: 192.168.100.2
     ansible_ssh_private_key_file: ../.vagrant/machines/db/virtualbox/private_key
  web:
   hosts:
    wordpress:
     ansible_host: 192.168.100.3
     ansible_ssh_private_key_file: ../.vagrant/machines/wp/virtualbox/private_key
