#########################################################
# Wordpress on Ubuntu 20.04 LAMP with php-fpm
#########################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/common.yml
  roles:
    - common

- hosts: base
  become: true
  vars_files:
    - vars/common.yml
  roles:
    - inst_base
    - conf_wp_base

- hosts: web
  become: true
  vars_files:
    - vars/common.yml
    - vars/wp_init.yml
  roles:
    - inst_web
    - conf_wp_web
